### ISSUE TITLE
change to &signer type!

### ISSUE THREAD

**Issue by Godxia** [pontem-network/liquidswap-docs#2]
Hello!  I have tested LiquidSwap. I found that the scripts module uses the signer type instead of the &signer type. I don't think it's very good. Because the signer type cannot be copied, functions in the Scripts module can only be called once per function. If some swaps need more than one route like [X->Y->Z] or someone plan to develop an aggregation dapp, it can not be realized. I think all the signer type should change to &signer type.

**Comment by borispovod** [comment]
Done in v0.3, expect this week on testnet.
