### ISSUE TITLE
The links in the doc are broken!

### ISSUE THREAD

**Issue by jackcpku** [pontem-network/liquidswap-docs#3]
Hi! I'm currently investigating into this project, but I'm having trouble accessing the source code. The repo containing smart contracts mentioned in the docs (https://github.com/pontem-network/liquidswap) seems nowhere to be found. Anyone knows where the codes are gone?

**Comment by borispovod** [comment]
Hey, 

Source code is closed, you can contact us and we can open it for you.
Once all audit passed we will open source it.

**Comment by borispovod** [comment]
It's open source, so closing now.
